package main

import (
	"embed"
	"flag"
	"fmt"
	"grianlang3/checker"
	"grianlang3/emitter"
	"grianlang3/lexer"
	"grianlang3/parser"
	"log"
	"os"
	"os/exec"
)

//go:embed builtins/*.ll
var builtinFs embed.FS

func main() {
	keepll := flag.Bool("keepll", false, "doesn't remove the .ll files generated by the grianlang3 compiler after compilation to exec")
	dbg := flag.Bool("dbg", false, "prints out the ast for every file compiled")
	noexecbuild := flag.Bool("noexecbuild", false, "prevents clang from linking an executable")
	flag.Parse()
	files := flag.Args()

	if err := os.RemoveAll("./lltemp"); err != nil {
		log.Fatal(err)
	}
	if err := os.Mkdir("./lltemp", os.ModePerm); err != nil {
		log.Fatal(err)
	}
	var llFiles []string
	builtinModules := map[string]struct{}{}
	for _, file := range files {
		input, err := os.ReadFile(file)
		if err != nil {
			log.Fatal(err)
		}

		l := lexer.New(string(input))
		p := parser.New(l)
		program := p.ParseProgram()
		err = safeRun(func() {
			if *dbg {
				log.Printf("%s: %s\n", file, program.String())
			}
		})
		if err != nil {
			log.Printf("%s: recovered printing dbg ast: %s\n", file, err)
		}
		if len(p.Errors) != 0 {
			for _, err := range p.Errors {
				log.Printf("parser error: %s:%s\n", file, err.String())
			}
			fatalAndCleanup(*keepll, "%s: exiting after parser errors\n", file)
		}
		c := checker.New()
		c.Check(program)
		if len(c.Errors) != 0 {
			for _, err := range c.Errors {
				log.Printf("checker warning: %s:%s\n", file, err.String())
			}
		}

		e := emitter.New()
		err = safeRun(func() {
			e.Emit(program)
		})
		if len(e.Errors) != 0 {
			for _, err := range e.Errors {
				log.Printf("compiler error: %s:%s\n", file, err.String())
			}
			fatalAndCleanup(*keepll, "exiting after compiler errors\n")
		}
		if err != nil {
			log.Printf("%s: recovered emitting llvm ir: %s\n", file, err)
			fatalAndCleanup(*keepll, "exiting after compiler panic\n")
		}
		llvmIr := e.Module()

		fileName := fmt.Sprintf("./lltemp/%s.ll", file)
		llFile, err := os.Create(fileName)
		if err != nil {
			fatalAndCleanup(*keepll, "%s: %v\n", file, err)
		}
		_, err = fmt.Fprintf(llFile, "%s", llvmIr)
		if err != nil {
			fatalAndCleanup(*keepll, "%s: %v\n", file, err)
		}
		err = llFile.Close()
		if err != nil {
			fatalAndCleanup(*keepll, "%s: %v\n", file, err)
		}

		llFiles = append(llFiles, fileName)

		for _, builtinModule := range e.BuiltinModules() {
			builtinModules[builtinModule] = struct{}{}
		}
	}

	for mod, _ := range builtinModules {
		modText, err := builtinFs.ReadFile(fmt.Sprintf("builtins/%s", mod))
		if err != nil {
			fatalAndCleanup(*keepll, "failed to read %s from builtin fs: %v\n", mod, err)
		}

		fileName := fmt.Sprintf("./lltemp/%s", mod)
		llFile, err := os.Create(fileName)
		if err != nil {
			fatalAndCleanup(*keepll, "failed to create %s: %v\n", llFile.Name(), err)
		}
		_, err = fmt.Fprintf(llFile, "%s", modText)
		if err != nil {
			fatalAndCleanup(*keepll, "failed to write %s: %v\n", llFile.Name(), err)
		}
		err = llFile.Close()
		if err != nil {
			fatalAndCleanup(*keepll, "failed to close %s: %v\n", llFile.Name(), err)
		}
		llFiles = append(llFiles, fileName)
	}

	llFiles = append(llFiles, "-o", "out")
	if !*noexecbuild {
		out, err := exec.Command("clang", llFiles...).CombinedOutput()
		if err != nil {
			fmt.Printf("out in clang exec: %s\n", out)
			fmt.Printf("err in clang exec: %v\n", err)
			fatalAndCleanup(*keepll, "existing after err in clang exec\n")
		}
	}
	if !*keepll {
		if err := os.RemoveAll("./lltemp"); err != nil {
			log.Fatal(err)
		}
	}
}

func fatalAndCleanup(keepll bool, fmt string, v ...any) {
	if !keepll {
		err := os.RemoveAll("./lltemp")
		if err != nil {
			log.Fatal(err)
		}
	}
	log.Fatalf(fmt, v...)
}

func safeRun(fn func()) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	fn()
	return nil
}
